version: '3.7'

services:
  frontend:
    image: node:latest # Use the image that matches your Node version
    build:
      context: ./vinyl-vault-frontend # Specify the path to your Angular app directory
      dockerfile: Dockerfile # You will need a Dockerfile to build the Angular app
    ports:
      - "8081:80"

  backend:
    image: maven:latest # Use the Maven image to build your Java app
    build:
      context: ./vinyl-vault-backend/vinylvaultback # Specify the path to your Maven project directory
      dockerfile: Dockerfile # You will need a Dockerfile to build the Java app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

